### ISSUE TITLE
npm run dev  Error 

### ISSUE THREAD

**Issue by mydearxym** [Famous/engine-seed#29]
i follow the [Guide](http://famous.org/get-started.html)  , but when i run `npm run dev` i get error: 

``` bash

 engine-seed git:(master) npm run dev

> engine-seed@1.0.0 dev /Users/xieyiming/code/famous/engine-seed
> node ./bin/dev.js

serving /Users/xieyiming/code/famous/engine-seed/public on port 1618

module.js:340
    throw err;
          ^
Error: Cannot find module 'glsl-tokenizer/string'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/xieyiming/code/famous/engine-seed/node_modules/famous/node_modules/glslify/node_modules/glslify-deps/index.js:1:78)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

npm ERR! engine-seed@1.0.0 dev: `node ./bin/dev.js`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the engine-seed@1.0.0 dev script.
npm ERR! This is most likely a problem with the engine-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/dev.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls engine-seed
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 14.1.1
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! cwd /Users/xieyiming/code/famous/engine-seed
npm ERR! node -v v0.10.24
npm ERR! npm -v 1.3.21
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/xieyiming/code/famous/engine-seed/npm-debug.log
npm ERR! not ok code 0

```

**Comment by mydearxym** [comment]
i have to install by my self  

``` bash
   "glsl-tokenizer": "~2.0.2",
   "graceful-fs": "~4.1.2",
   "map-limit": "0.0.1",
   "inherits": "~2.0.1"
```

and then : 

``` bash
engine-seed git:(master) ✗ npm run dev

> engine-seed@1.0.0 dev /Users/xieyiming/code/famous/engine-seed
> node ./bin/dev.js

serving /Users/xieyiming/code/famous/engine-seed/public on port 1618

module.js:340
    throw err;
          ^
Error: Cannot find module 'events/'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/xieyiming/code/famous/engine-seed/node_modules/famous/node_modules/glslify/node_modules/glslify-deps/index.js:5:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

what's going on ?

**Comment by laneallen** [comment]
I just installed the engine-seed without any problems. It looks like you're running into permission issues from the errors shown, e.g. `npm ERR! Exit status 8` (http://stackoverflow.com/questions/21960111/node-js-express-npm-start-error-exit-status-8#21960610) and all the `npm ERR!`'s.

You could either install/run with `sudo` or fix your npm issues so you won't have those problems anymore:
https://docs.npmjs.com/getting-started/fixing-npm-permissions
